name: build-db
on:
  push:
    branches:
      - 'master'  # only default branch
  pull_request:

concurrency:
  group: ${{ github.head_ref }} || concat(${{ github.ref }}, ${{ github.workflow }})
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        # the result of the matrix will be the combination of all attributes, so we get os*compiler*modules builds
        os: [ubuntu-20.04]
        compiler: [clang]
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.compiler }}
    env:
      COMPILER: ${{ matrix.compiler }}
    if: github.repository == 'azerothcore/azerothcore-wotlk' && !github.event.pull_request.draft
    steps:
      - uses: actions/checkout@v4
      - name: Cache
        uses: actions/cache@v3
        env:
          cache-name: cache-db
        with:
          path: var/ccache
          key: ${{ env.cache-name }}-${{ matrix.os }}-${{ matrix.compiler }}-${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            ${{ env.cache-name }}-${{ matrix.os }}-${{ matrix.compiler }}-${{ github.ref }}-
            ${{ env.cache-name }}-${{ matrix.os }}-${{ matrix.compiler }}-
            ${{ env.cache-name }}-${{ matrix.os }}-
      - name: Configure OS
        run: source ./acore.sh install-deps
        env:
          CONTINUOUS_INTEGRATION: true
      - name: Create conf/config.sh
        run: source ./apps/ci/ci-conf-db.sh
      - name: Build
        run: source ./apps/ci/ci-compile.sh
      - name: Process pending sql
        run: bash bin/acore-db-pendings
      - name: Dry run
        run: source ./apps/ci/ci-dry-run.sh dbimport
