name: Codestyle
on:
  pull_request:
    paths:
      - src/**
      - "!README.md"
      - "!docs/**"

jobs:
  triage:
    runs-on: ubuntu-latest
    name: C++
    if: github.repository == 'liyunfan1223/azerothcore-wotlk'
    steps:
      - uses: actions/checkout@v4
      - name: AzerothCore codestyle
        run: source ./apps/ci/ci-codestyle.sh
      - name: C++ Advanced
        run: |
          sudo apt update -y
          sudo apt install -y cppcheck
          cppcheck --force --inline-suppr --suppressions-list=./.suppress.cppcheck src/ --output-file=report.txt

          if [ -s report.txt ]; then  # if file is not empty
            cat report.txt
            exit 1 # let github action fails
          fi
