name: nopch-module-build
on:
  push:
    branches:
      - 'master'
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - 'src/*'
      - 'src/common/**/*'
      - 'src/genrev/**/*'
      - 'src/server/*'
      - 'src/server/apps/**/*'
      - 'src/server/database/**/*'
      - 'src/server/game/**/*'
      - 'src/server/shared/**/*'
      - 'src/tools/**/*'

concurrency:
  group: ${{ github.head_ref }} || concat(${{ github.ref }}, ${{ github.workflow }})
  cancel-in-progress: true

jobs:
  build-modules:
    strategy:
      fail-fast: true
      matrix:
        include:
          - os: ubuntu-24.04
            compiler:
              CC: clang-18
              CXX: clang++-18
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}-${{ matrix.compiler.CC }}-nopch-modules
    if: github.repository == 'azerothcore/azerothcore-wotlk' && !github.event.pull_request.draft
    steps:
      - uses: actions/checkout@v4
        # This script installs a general list of modules to compile with
        # azerothcore. This is useful for ensuring that module compilation
        # functionality works.
      - name: Checkout modules
        run: bash -x ./apps/ci/ci-install-modules.sh
      - uses: ./.github/actions/linux-build
        with:
          CC: ${{ matrix.compiler.CC }}
          CXX: ${{ matrix.compiler.CXX }}
          modules: true
          pch: false
          maxerrors: 0
          keepgoing: true
