name: pch-build
on:
  push:
    branches:
      - 'master'
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

concurrency:
  group: ${{ github.head_ref }} || concat(${{ github.ref_name }}, ${{ github.workflow }})
  cancel-in-progress: true

permissions:
  actions: write
  contents: read

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        include:
          - os: ubuntu-22.04
            compiler:
              CC: clang-15
              CXX: clang++-15
          - os: ubuntu-24.04
            compiler:
              CC: clang-18
              CXX: clang++-18
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}-${{ matrix.compiler.CC }}-pch
    if: github.event.pull_request.base.repo.full_name == github.repository
    echo "Target / Base Repo: base.repo.full_name: ${{ github.event.pull_request.base.repo.full_name }}"
    echo "Current Repo: github.repository: ${{ github.repository }}"  
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/linux-build
        with:
          CC: ${{ matrix.compiler.CC }}
          CXX: ${{ matrix.compiler.CXX }}
          pch: true
