name: pch-build
on:
  push:
    branches:
      - 'master'
  pull_request:
    types: ['opened', 'synchronize', 'reopened']

concurrency:
  group: ${{ github.head_ref }} || concat(${{ github.ref }}, ${{ github.workflow }})
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-20.04
            compiler:
              CC: gcc-10
              CXX: g++-10
          - os: ubuntu-20.04
            compiler:
              CC: clang-12
              CXX: clang++-12
          - os: ubuntu-22.04
            compiler:
              CC: clang-15
              CXX: clang++-15
          - os: ubuntu-22.04
            compiler:
              CC: gcc-12
              CXX: g++-12
          - os: ubuntu-24.04
            compiler:
              CC: clang-18
              CXX: clang++-18
          - os: ubuntu-24.04
            compiler:
              CC: gcc-14
              CXX: g++-14
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}-${{ matrix.compiler }}-pch
    env:
      COMPILER: ${{ matrix.compiler }}
    if: github.repository == 'liyunfan1223/azerothcore-wotlk' && !github.event.pull_request.draft
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/linux-build
        with:
          CC: ${{ matrix.compiler.CC }}
          CXX: ${{ matrix.compiler.CXX }}
          pch: true
