name: nopch-module-build
on:
  push:
    branches:
      - 'master'
  pull_request:
    types: ['labeled', 'opened', 'synchronize', 'reopened']

concurrency:
  group: ${{ github.head_ref }} || concat(${{ github.ref }}, ${{ github.workflow }})
  cancel-in-progress: true

jobs:
  build-modules:
    runs-on: ubuntu-latest
    name: modules build on latest ubuntu
    if: |
      github.repository == 'azerothcore/azerothcore-wotlk'
      && !github.event.pull_request.draft
      && (
        github.ref_name == 'master'
        || contains(github.event.pull_request.labels.*.name, 'file-cpp'
        || github.event.label.name == 'file-cpp'
        || contains(github.event.pull_request.labels.*.name, 'run-build')
        || github.event.label.name == 'run-build')
      )
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/linux-build
        with:
          CC: clang-15
          CXX: clang++-15
          modules: true
          pch: false
