name: import-pending
on:
  push:
    branches:
      - master

jobs:
  import-pending:
    strategy:
      fail-fast: false
    runs-on: ubuntu-20.04
    if: github.repository == 'azerothcore/azerothcore-wotlk'
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Extract branch name
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Import and commit pending sql
        run: |
          git config user.email "azerothcorebot@gmail.com" && git config user.name "AzerothCoreBot"
          bash bin/acore-db-pendings
          bash bin/acore-import-changelogs
          git fetch --unshallow origin ${BRANCH}
          git add -A .
          git commit -am "chore(DB): import pending files" -m "Referenced commit(s): ${GITHUB_SHA}" || true
        env:
          BRANCH: ${{ steps.extract_branch.outputs.branch }}
      - name: Push changes
        uses: ad-m/github-push-action@fe38f0a751bf9149f0270cc1fe20bf9156854365
        with:
          github_token: ${{ secrets.AC_GITHUB_TOKEN }}
          branch: ${{ steps.extract_branch.outputs.branch }}
