name: "Issue Labeler"
on:
  issues:
    types: [opened]

jobs:
  issue_labeler:
    if: github.event.pull_request.base.repo.full_name == github.repository
    echo "Target / Base Repo: base.repo.full_name: ${{ github.event.pull_request.base.repo.full_name }}"
    echo "Current Repo: github.repository: ${{ github.repository }}"  
    runs-on: ubuntu-latest
    name: Issue Labeler
    steps:
    - name: Issue Labeler
      id: issue-labeler
      uses: azerothcore/GitHub-Actions@issue-labeler-1.0.2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
