on:
  issues:
    types: [opened]

jobs:
  issue_labeler:
    if: github.repository == 'azerothcore/azerothcore-wotlk'
    runs-on: ubuntu-latest
    name: Issue Labeler
    steps:
    - name: Issue Labeler
      id: issue-labeler
      uses: azerothcore/GitHub-Actions@issue-labeler-1.0.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
