name: PR Labeler
on:
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review] # Run the Labeler on Opened, Synced, Re-opened or Ready for Review (from Draft to Live)

jobs:
  triage:
    runs-on: ubuntu-24.04
    permissions: write-all
    if: github.repository == 'azerothcore/azerothcore-wotlk' && !github.event.pull_request.draft
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true
      - uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yml
          sync-labels: false # True = Overite existing Labels | False = Add Labels
