name: PR Labeler
on:
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review] # Ready for Review = Draft to Live PR

jobs:
  triage:
    runs-on: ubuntu-24.04
    permissions: write-all
    if: github.event.pull_request.base.repo.full_name == github.repository
    echo "Target / Base Repo: base.repo.full_name: ${{ github.event.pull_request.base.repo.full_name }}"
    echo "Current Repo: github.repository: ${{ github.repository }}"  
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true
      - uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yml
          sync-labels: false # true = Removes ALL current labels before adding the labels | false = Only adds the Labels
