name: SQL Codestyle
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - data/**
      - "!README.md"
      - "!docs/**"

jobs:
  triage:
    runs-on: ubuntu-latest
    name: SQL
    if: github.event.pull_request.base.repo.full_name == github.repository
    echo "Target / Base Repo: base.repo.full_name: ${{ github.event.pull_request.base.repo.full_name }}"
    echo "Current Repo: github.repository: ${{ github.repository }}"  
    steps:
      - name: Repo Check
        run: |
          echo "Target / Base Repo: base.repo.full_name: ${{ github.event.pull_request.base.repo.full_name }}"
          echo "Current Repo: github.repository: ${{ github.repository }}"
      - uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: AzerothCore codestyle
        run: python ./apps/codestyle/codestyle-sql.py
