name: tools
on:
  push:
    branches:
      - 'master'
  pull_request:
    types:
      - labeled
      - synchronize

concurrency:
  group: ${{ github.head_ref }} || concat(${{ github.ref_name }}, ${{ github.workflow }})
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        include:
          - os: ubuntu-24.04
            compiler:
              CC: clang-18
              CXX: clang++-18
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}-${{ matrix.compiler.CC }}
    if: |
      github.event.pull_request.base.repo.full_name == github.repository
    echo "Target / Base Repo: base.repo.full_name: ${{ github.event.pull_request.base.repo.full_name }}"
    echo "Current Repo: github.repository: ${{ github.repository }}"  
      && !github.event.pull_request.draft
      && (github.ref == 'refs/heads/master' || contains(github.event.pull_request.labels.*.name, 'run-build') || github.event.label.name == 'run-build')
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/linux-build
        with:
          CC: ${{ matrix.compiler.CC }}
          CXX: ${{ matrix.compiler.CXX }}
          tools: all
          pch: false
