name: windows-build
on:
  push:
    branches:
      - 'master'
  pull_request:
    types: ['labeled']

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  windows-build:
    strategy:
      fail-fast: false
    runs-on: windows-2019
    name: windows-2019-MSVC16
    env:
      BOOST_ROOT: C:\local\boost_1_74_0
    if: github.repository == 'azerothcore/azerothcore-wotlk && ${{ github.event.label.name == 'run-build' }}'
    steps:
      - uses: actions/checkout@v2
      - name: Configure OS
        run: choco install --no-progress openssl boost-msvc-14.2
      - name: Build
        shell: bash
        run: |
          mkdir -p build && cd build
          cmake .. -DTOOLS=ON
          cmake --build . --config Release --parallel 4
      - name: Copy dll files
        shell: bash
        run: |
          cp "/c/mysql-5.7.21-winx64/lib/libmysql.dll" "build/bin/Release/"
          cp "/c/Program Files/OpenSSL-Win64/bin/libcrypto-1_1-x64.dll" "build/bin/Release/"
          cp "/c/Program Files/OpenSSL-Win64/bin/libssl-1_1-x64.dll" "build/bin/Release/"
      - uses: actions/upload-artifact@v2
        with:
          name: windows-2019-MSVC16-release
          path: build/bin/Release
