name: windows-build-mip
on:
  push:
    tags:        
      - '**'
  #   branches:
  #     - 'master'
  # pull_request:
  #   types: ['labeled', 'opened', 'synchronize', 'reopened']

concurrency:
  group: ${{ github.head_ref }} || concat(${{ github.ref }}, ${{ github.workflow }})
  cancel-in-progress: true

jobs:
  windows-build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}
    env:
      BOOST_ROOT: C:\local\boost_1_79_0
    if: |
      github.repository == 'AlvinZhu/azerothcore-wotlk'
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Configure OS
        shell: bash
        env:
          CONTINUOUS_INTEGRATION: true
        run: |
          ./acore.sh install-deps
      # - name: Process pending sql
      #   shell: bash
      #   run: bash bin/acore-db-pendings
      - name: Build
        shell: bash
        run: |
          export CTOOLS_BUILD=all
          ./acore.sh compiler build
      # - name: Dry run authserver
      #   shell: bash
      #   run: |
      #     source ./apps/ci/ci-gen-server-conf-files.sh "authserver" "configs" "."
      #     cd env/dist
      #     ./authserver -dry-run
      # - name: Dry run worldserver
      #   shell: bash
      #   run: |
      #     source ./apps/ci/ci-gen-server-conf-files.sh "worldserver" "configs" "."
      #     cd env/dist
      #     ./worldserver -dry-run
      # - name: Stop MySQL
      #   run: net stop mysql
      - name: Copy dll files
        shell: bash
        run: |
          rm -rf env/dist/data
          cp "/c/tools/mysql/current/lib/libmysql.dll" "env/dist"
      # cp "/c/Program Files/OpenSSL-Win64/bin/libcrypto-1_1-x64.dll" "env/dist"
      # cp "/c/Program Files/OpenSSL-Win64/bin/libssl-1_1-x64.dll" "env/dist"
      - uses: actions/upload-artifact@v3
        with:
          name: windows-2022-MSVC17-release
          path: env/dist
